---
- name: Start chrony
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true

- name: Start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
